### ISSUE TITLE
Not working in Windows 8 x64

### ISSUE THREAD

**Issue by bricss** [curvedmark/roole#47]
Can't compile any *.roo file in windows environment (Nodejs v0.8.20).
This is what in my console log:

C:>roole .\style.roo

C:\Users\Troy\AppData\Roaming\npm\node_modules\roole\lib\roole.js:35
                                        input = options.imports[error.filePath]
                                                               ^
TypeError: Cannot read property '.\style.roo' of undefined
    at roole.compile.callback (C:\Users\Troy\AppData\Roaming\npm\node_modules\ro
ole\lib\roole.js:35:29)
    at Object.roole.compile (C:\Users\Troy\AppData\Roaming\npm\node_modules\rool
e\lib\roole.js:50:10)
    at compileFile (C:\Users\Troy\AppData\Roaming\npm\node_modules\roole\bin\roo
le:111:8)
    at C:\Users\Troy\AppData\Roaming\npm\node_modules\roole\bin\roole:92:4
    at Array.forEach (native)
    at compileFiles (C:\Users\Troy\AppData\Roaming\npm\node_modules\roole\bin\ro
ole:85:8)
    at Object.<anonymous> (C:\Users\Troy\AppData\Roaming\npm\node_modules\roole\
bin\roole:68:2)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)

C:>roole C:\style.roo

fs.js:524
  return binding.stat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory 'C:\C'
    at Object.fs.statSync (fs.js:524:18)
    at C:\Users\Troy\AppData\Roaming\npm\node_modules\roole\bin\roole:89:17
    at Array.forEach (native)
    at compileFiles (C:\Users\Troy\AppData\Roaming\npm\node_modules\roole\bin\ro
ole:85:8)
    at Object.<anonymous> (C:\Users\Troy\AppData\Roaming\npm\node_modules\roole\
bin\roole:68:2)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)

C:>roole %CD%\style.roo

fs.js:524
  return binding.stat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory 'C:\C'
    at Object.fs.statSync (fs.js:524:18)
    at C:\Users\Troy\AppData\Roaming\npm\node_modules\roole\bin\roole:89:17
    at Array.forEach (native)
    at compileFiles (C:\Users\Troy\AppData\Roaming\npm\node_modules\roole\bin\ro
ole:85:8)
    at Object.<anonymous> (C:\Users\Troy\AppData\Roaming\npm\node_modules\roole\
bin\roole:68:2)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)

C:>roole style.roo

C:\Users\Troy\AppData\Roaming\npm\node_modules\roole\lib\roole.js:35
                                        input = options.imports[error.filePath]
                                                               ^
TypeError: Cannot read property 'style.roo' of undefined
    at roole.compile.callback (C:\Users\Troy\AppData\Roaming\npm\node_modules\ro
ole\lib\roole.js:35:29)
    at Object.roole.compile (C:\Users\Troy\AppData\Roaming\npm\node_modules\rool
e\lib\roole.js:50:10)
    at compileFile (C:\Users\Troy\AppData\Roaming\npm\node_modules\roole\bin\roo
le:111:8)
    at C:\Users\Troy\AppData\Roaming\npm\node_modules\roole\bin\roole:92:4
    at Array.forEach (native)
    at compileFiles (C:\Users\Troy\AppData\Roaming\npm\node_modules\roole\bin\ro
ole:85:8)
    at Object.<anonymous> (C:\Users\Troy\AppData\Roaming\npm\node_modules\roole\
bin\roole:68:2)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)

C:>

**Comment by bricss** [comment]
After uninstalling "npm rm -g roole" & clean up all npm directories problem were fixed.

P.S.: Thank you for your great job! I will start new project with Roole!
