### ISSUE TITLE
Missing correct variable for empty roo file

### ISSUE THREAD

**Issue by bricss** [curvedmark/roole#51]
``` console
roole -o ./css/ -w ./roole/*.roo

/usr/local/lib/node_modules/roole/bin/roole:104
    console.log('INFO: ' + inputFile + ' compiles to empty string, no file cre
                           ^
ReferenceError: inputFile is not defined
    at /usr/local/lib/node_modules/roole/bin/roole:104:28
    at Array.forEach (native)
    at /usr/local/lib/node_modules/roole/bin/roole:102:9
    at /usr/local/lib/node_modules/roole/bin/roole:127:6
    at /usr/local/lib/node_modules/roole/bin/roole:164:3
    at roole.compile.callback (/usr/local/lib/node_modules/roole/lib/roole.js:40:4)
    at roole.compile (/usr/local/lib/node_modules/roole/lib/roole.js:68:3)
    at Importer.visitImport (/usr/local/lib/node_modules/roole/lib/importer/importer.js:113:4)
    at fs.readFile (fs.js:176:14)
    at Object.oncomplete (fs.js:297:15)
```

replace

``` javascript
console.log('INFO: ' + inputFile + ' compiles to empty string, no file created')
```

to

``` javascript
console.log('INFO: ' + file.origPath + ' compiles to empty string, no file created')
```

**Comment by curvedmark** [comment]
Thanks, fixed in v0.2.2.
